name: Setup and Run main.py

on:
  schedule:
    - cron: '15 */6 * * *'  # Runs every 6 hours and 1 minute
  workflow_dispatch:  # Allows manual triggering

jobs:
  stream_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: Install Python dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install requests  # Add other dependencies here if needed

      - name: Download video from Dropbox
        run: |
          curl -L -o "video.mp4" "https://www.dropbox.com/scl/fi/lz1khkvahf5rcp5obbnn6/Ip-is-1-1.mp4?rlkey=jlxf0s2v97ngj2y6oxamvnlpy&raw=1"
      
      - name: Run main.py
        run: timeout 6h python3 main.py
